let rule_prefix = "where"
let start_match_pattern = "match"
let start_rewrite_pattern = "rewrite"
let equal = "=="
let not_equal = "!="
let variable_left_delimiter = ":["
let variable_right_delimiter = "]"
let true' = "true"
let false' = "false"
let pipe_operator = "|"
let arrow = "->"

let option_nested = "nested"
let option_loose_whitespace = "loose-whitespace"

let separator = "---"
